version: '3'

services:
  kafka:
    networks:
      - network_ben
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
    # depends_on:
      # - sqlserver1

  producer:
    networks:
      - network_ben
    depends_on:
      - kafka
    build:
      context: ./producer
      dockerfile: Dockerfile

  consumer:
    image: docker.io/bitnami/dotnet-sdk:6
    networks:
      - network_ben
    depends_on:
      - producer
    build:
      context: ./consumer
      dockerfile: Dockerfile
    command: dotnet run
    volumes:
      - sqlite_volume:/appcsharp

  api1:
    image: docker.io/bitnami/dotnet-sdk:6
    networks:
      - network_ben
    build:
      context: ./api1
      dockerfile: Dockerfile
    ports:
      - "5287:5287"
    command: dotnet run
    volumes:
      - sqlite_volume:/api1
    # depends_on:
    #   - producer

  # sqlserver1:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   networks:
  #     - network_ben
  #   environment:
  #     ACCEPT_EULA: ${DB1_ACCEPT_EULA}
  #     MSSQL_SA_PASSWORD: ${DB1_MSSQL_SA_PASSWORD}
  #     MSSQL_PID: ${DB1_MSSQL_PID}
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - ./db/db1:/var/opt/mssql/data

networks:
  network_ben:
    driver: bridge

volumes:
  sqlite_volume:
    driver_opts:
      o: bind
      type: none
      device: ./sqlite
