version: '3.4'

services:
  sqlserver2:
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      - network_ben2
    environment:
      ACCEPT_EULA: ${DB2_ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${DB2_MSSQL_SA_PASSWORD}
      MSSQL_PID: ${DB2_MSSQL_PID}
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", -Slocalhost, "-U${DB2_MSSQL_USER}", "-P${DB2_MSSQL_SA_PASSWORD}", "-Q", "SELECT 1"]
      interval: 5s
      retries: 20
    ports:
      - "1434:1433"
    volumes:
      - ../db/db2:/var/opt/mssql/data

  api2:
    networks:
      - network_ben2
    depends_on:
      sqlserver2:
        condition: service_healthy
    environment:
      DB_SERVER: ${DOCKER_DB2_MSSQL_HOST}
      DB_USER: ${DB2_MSSQL_USER}
      DB_PASS: ${DB2_MSSQL_SA_PASSWORD}
    build:
      context: ./backend_python
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  network_ben2:
    driver: bridge