"""Initial migration

Revision ID: f03a10113f59
Revises: ef4a0a7b82a9
Create Date: 2023-07-06 15:10:41.366066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03a10113f59'
down_revision = 'ef4a0a7b82a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
